import { Theme } from "@/components/ui/theme-provider";

export const defaultTheme: Theme = {
  name: "default",
  colors: {
    primary: "#2BBAEE",
    primaryForeground: "#FFFFFF",
    secondary: "#90FDF2",
    secondaryForeground: "#1A1A1A",
    accent: "#E2E8F0",
    accentForeground: "#1A1A1A",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    error: "#EF4444",
    errorForeground: "#FFFFFF",
    info: "#3B82F6",
    infoForeground: "#FFFFFF",
    background: "#0A0A0A",
    foreground: "#F3F4F6",
    muted: "#1F2937",
    mutedForeground: "#9CA3AF",
    border: "#374151",
    focusRing: "#3B82F6",
    selection: "#3B82F6",
    selectionForeground: "#FFFFFF",
  },
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    bold: false,
    sm: "12px",
    base: "14px",
    lg: "16px",
    xl: "20px",
  },
  border: {
    style: "single",
    color: "#374151",
    focusColor: "#3B82F6",
  },
};
